#!/usr/bin/python3
from sys import argv

def factorize(num):
    """
        Factorize as many numbers as possible into a product of two smaller numbers.
    """
    multifactor = 2

    if num < 2:
        return
    while multifactor <= num / 2:
        if num % multifactor == 0 and multifactor <= num /multifactor:
            print("{:.0f}={:.0f}*{:.0f}".format(num, num / multifactor, multifactor))
        multifactor += 1

if len(argv) != 2:
    exit()
else:
    try:
        with open(argv[1]) as file:
            row = file.readline()
            while row != "":
                num = row.split('\n')[0]
                factorize(int(num))
                row = file.readline()
    except Exception:
        pass
